# Generated by Django 2.1.5 on 2019-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_post_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
